Python comes with a lot of functions, but most of them
are not available when you start a program.
For example, pretty much any programming language will have a function
to calculate the sine of a number.
My normal development environment for python has over seventy thousand functions
defined in it!

It would be madness if every function ever defined was always accessible.
Plus, you'd have collisions. A program that reads `bed` files from disk might have a
function called `open`, and a program that creates a database connection might also
have a function called `open`. 

To deal with this, Python uses a module system. 
A module is a file containing Python code with function
definitions (and possibly other stuff) that you can load up using the
`import` statement.

In [1]:
import math

You'll notice that the import statement didn't create any output.
What it did is it read in the file containing Python's math functions.
I can name a function from that module to use it.

In [2]:
print(math.sin(10))

-0.5440211108893698


You can create your own modules, too, but you can't easily do it with
Jupyter notebooks, so I won't cover that here.


In [3]:
# There's another syntax you can use to import specific names from modules
from random import randint
print("the die rolled a ", randint(1,6))

the die rolled a  3


The `from x import y` syntax means that you can just refer to `y` and not
have to write `x.y` to get the same effect.
In general, I prefer the first form because it makes it clear in your code
where your functions are coming from.
If I were deep in your code and I saw a call to `gaussian_filter1d`, I wouldn't know
if that were a function you defined in the same file or something from a module.
but if I saw `signal.gaussian_filter1d`, I'd know immediately that it was from a module.

In [4]:
# Oh, one last thing: you can rename imports, like this:
import numpy as np
def makeAr():
    x = np.zeros((5,5))
    print(x)

This is very handy when you're using a module with a long name
a lot in your code, so you can say
`import scipy.image_processing.filter_utilities.convolutional_filters as filters`
and then just have
`x = filters.gaussian_filter1d(image)`
instead of the whole entire name of the package.

In [5]:
makeAr()

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
